name: SkillsSync
options:
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: "6.0"
    MACOSX_DEPLOYMENT_TARGET: "15.0"
    DEVELOPMENT_TEAM: AK7R88WBZ6
    CODE_SIGN_STYLE: Automatic
    CODE_SIGN_IDENTITY: Apple Development

targets:
  SkillsSyncApp:
    type: application
    platform: macOS
    sources:
      - Sources/Shared
      - Sources/App
    info:
      path: App/App-Info.plist
      properties:
        CFBundleURLTypes:
          - CFBundleURLName: dev.fedosov.skillssync.url
            CFBundleURLSchemes:
              - skillssync
    entitlements:
      path: App/SkillsSyncApp.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.application-groups:
          - group.dev.fedosov.skillssync
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: dev.fedosov.skillssync.app
        PRODUCT_NAME: SkillsSyncApp

  SkillsSyncTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - Tests/SkillsSyncTests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: dev.fedosov.skillssync.tests
        GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: SkillsSyncApp
